"""Independent regression checks for the QPC1 aggregate-only public package."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import re
import shutil
import sys
from pathlib import Path


sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1] / "evaluation-results" / "hbq-qpc1-figurative-treatment-v1"
AGGREGATE = ROOT / "qpc1-public-aggregate.v1.json"
EXPECTED_SHA256 = "7f81bcc76ff33579c92916d1d1299a046bc6f15235e777e719a7e0e59f0b020a"


def _verifier():
    path = ROOT / "verify_output.py"
    spec = importlib.util.spec_from_file_location("qpc1_public_verifier", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_public_qpc1_package_verifies_with_its_local_command_contract() -> None:
    assert _verifier().check(ROOT) == []


def test_public_qpc1_aggregate_has_exact_allowlisted_shape_and_arithmetic() -> None:
    data = json.loads(AGGREGATE.read_text(encoding="utf-8"))
    assert set(data) == {
        "format_version",
        "study_id",
        "public_cwr_parent",
        "protocol_geometry",
        "public_leaf_ids",
        "artifact_roles",
        "aggregate_counts",
        "limitations",
        "sealed_private_receipt_commitments",
    }
    geometry = data["protocol_geometry"]
    counts = data["aggregate_counts"]
    assert data["artifact_roles"] == [
        "author_original",
        "gpt_5_6_pro_rewrite",
        "public_control_story",
    ]
    assert len(data["public_leaf_ids"]) == geometry["selected_leaves"] == 7
    assert geometry["artifacts"] * geometry["repetitions_per_artifact"] == geometry["logical_runs"] == 15
    assert geometry["artifacts"] * geometry["selected_leaves"] == counts["artifact_leaf_cells"] == 21
    assert counts["artifact_leaf_cells"] * geometry["repetitions_per_artifact"] == counts["accepted_checkpoints"] == 105
    assert counts["accepted_verdicts"] == counts["accepted_yes"] == 105
    assert counts["accepted_no"] == counts["rejected_attempts"] == 0
    assert counts["provider_retry_or_validation_repair_events"] == 0


def test_public_qpc1_aggregate_digest_is_pinned() -> None:
    assert hashlib.sha256(AGGREGATE.read_bytes()).hexdigest() == EXPECTED_SHA256


def test_public_qpc1_reader_text_is_aggregate_only_and_discloses_limits() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    for claim in (
        "negative, no-discrimination result",
        "`author_original`",
        "`gpt_5_6_pro_rewrite`",
        "`public_control_story`",
        "`no_default_metaphors`, the stockness owner, was not selected",
        "complete-scope status was not rendered into the actual model-facing\ninstruction",
        "Two long works used a short-story bundle",
        "QPC24 is held",
        "does not justify a split,\nreweight, or a new density leaf",
    ):
        assert claim in readme
    for forbidden in (
        r"[A-Za-z]:[\\/]",
        r"(?:^|[\\/])(?:Users|home)(?:[\\/]|$)",
        r"\.private",
        r"session_id",
        r"request_id",
        r"run_id",
        r"blind_id",
        r"raw_prompt",
        r"raw_response",
        r"(?:source|story)_sha",
        r"(?:input|output|source)_path",
        r"exact_quote",
        r"qpc1-(?:aster|bramble|cinder)-\d+",
    ):
        assert not re.search(forbidden, readme, flags=re.IGNORECASE)


def test_verifier_rejects_nested_file_and_private_identifier(tmp_path: Path) -> None:
    candidate = tmp_path / "qpc1"
    shutil.copytree(ROOT, candidate)
    nested = candidate / "unexpected"
    nested.mkdir()
    (nested / "record.txt").write_text("aggregate-only package must not grow\n", encoding="utf-8")
    readme = candidate / "README.md"
    readme.write_text(
        readme.read_text(encoding="utf-8")
        + "\nC:\\Users\\synthetic\\qpc1-aster-17\\n",
        encoding="utf-8",
    )
    failures = _verifier().check(candidate)
    assert any("allowlist" in failure for failure in failures)
    assert any("forbidden public metadata: Windows path" == failure for failure in failures)
    assert any("forbidden public metadata: known blind alias" == failure for failure in failures)


def test_verifier_rejects_bytecode_cache(tmp_path: Path) -> None:
    candidate = tmp_path / "qpc1"
    shutil.copytree(ROOT, candidate)
    cache = candidate / "__pycache__"
    cache.mkdir()
    (cache / "verify_output.cpython-312.pyc").write_bytes(b"generated bytecode")
    assert any("allowlist" in failure for failure in _verifier().check(candidate))
